# This file is a special file that is used to publish my Google Summer of Code 2023 final report to my jekyll website.
# Link: https://k0t0z.github.io/posts/2023/GSoC_2023_final_evaluation_report.html

name: Publish Google Summer of Code 2023 final report

on:
    workflow_run:
      workflows: ["Jekyll: Render website"]
      types:
        - completed
      branches:
        - master-ready

jobs:
  move-file:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check if the rendering workflow was successful
        run: |
          if [ ${{ github.event.workflow_run.conclusion }} != "success" ]; then
            echo "The Jekyll rendering workflow was not successful. Exiting..."
            exit 1
          fi

      - name: Checkout master-ready branch
        uses: actions/checkout@v4
        with:
          ref: master-published

      - name: Download the report files from the master-ready branch
        run: |
          url="https://raw.githubusercontent.com/k0T0z/k0T0z.github.io/master-ready/special"

          # Download individual files
          curl -sLOk "$url/GSoC_2023_final_evaluation_report.html"
          curl -sLOk "$url/css/gsoc-2023-final-evaluation-report.css"
          curl -sLOk "$url/assets/arrow_outward.svg"
          curl -sLOk "$url/assets/logo-enigma.png"
          curl -sLOk "$url/assets/logo-gsoc.svg"
          curl -sLOk "$url/assets/my-google-summer-of-code-2023-proposal.pdf"
          
          # View the downloaded files' structure
          ls

      - name: Organize the report files
        run: |
          mkdir -p posts/2023/ posts/2023/css/ posts/2023/assets/
          mv GSoC_2023_final_evaluation_report.html posts/2023/
          mv gsoc-2023-final-evaluation-report.css posts/2023/css/
          mv arrow_outward.svg posts/2023/assets/
          mv logo-enigma.png posts/2023/assets/
          mv logo-gsoc.svg posts/2023/assets/
          mv my-google-summer-of-code-2023-proposal.pdf posts/2023/assets/

      - name: Commit and push the report to master-published
        run: |
          git config user.email "74428638+k0T0z@users.noreply.github.com"
          git config user.name "Saif Kandil"
          git add posts/2023/*
          git commit -m "Publish Google Summer of Code 2023 final report"
          git push origin master-published
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
